name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://npm.pkg.github.com
          scope: "@lastcallmedia"
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish
        run: |
          npm version --no-git-tag-version ${GITHUB_REF#"refs/tags/"}
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
